use_frameworks!

platform :ios, '8.0'

target 'wgPersonInfoCatogeryKit_Example' do
  pod 'wgPersonInfoCatogeryKit', :path => '../'

  target 'wgPersonInfoCatogeryKit_Tests' do
    inherit! :search_paths

    
  end
end
